from time import sleep
from userbot import CMD_HELP, bot
from userbot.events import register
from telethon import events
import asyncio


@register(outgoing=True, pattern="^.sayang$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("**I Love You** 💕")
        sleep(1)
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💘💞💗💕")
        await e.edit("💘💞💕💗")
        await e.edit("**I Miss You** 💝💖💘")
        sleep(1)
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💘💞💕💗")
        await e.edit("**Sayang**")
        await e.edit("**Kamu**")
        await e.edit("**Selamanya** 💕")
        sleep(1)
        await e.edit("💘💘💘💘")
        await e.edit("**Sayang**")
        await e.edit("**Kamu**")
        await e.edit("**Sayang**")
        await e.edit("**Kamu**")
        await e.edit("**I Love You**")
        sleep(1)
        await e.edit("**Baby**")
        await e.edit("💕💞💘💝")
        await e.edit("💘💕💞💝")
        await e.edit("**Love You** 💞")


@register(outgoing=True, pattern='^.anjing(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`Anjing gua lama amat.....`")
    sleep(1)
    await typew.edit("`Doggyyy!!!`")
    sleep(1)
    await typew.edit("`🏃                        🐕`")
    await typew.edit("`🏃                       🐕`")
    await typew.edit("`🏃                      🐕`")
    await typew.edit("`🏃                     🐕`")
    await typew.edit("`🏃   Cepat!!          🐕`")
    await typew.edit("`🏃                   🐕`")
    await typew.edit("`🏃                  🐕`")
    await typew.edit("`🏃                 🐕`")
    await typew.edit("`🏃                🐕`")
    await typew.edit("`🏃               🐕`")
    await typew.edit("`🏃              🐕`")
    await typew.edit("`🏃             🐕`")
    await typew.edit("`🏃            🐕`")
    await typew.edit("`🏃           🐕`")
    await typew.edit("`🏃Ayoo!!!   🐕`")
    await typew.edit("`🏃           🐕`")
    await typew.edit("`🏃            🐕`")
    await typew.edit("`🏃             🐕`")
    await typew.edit("`🏃              🐕`")
    await typew.edit("`🏃               🐕`")
    await typew.edit("`🏃                🐕`")
    await typew.edit("`🏃                 🐕`")
    await typew.edit("`🏃                  🐕`")
    await typew.edit("`🏃                   🐕`")
    await typew.edit("`🏃                    🐕`")
    await typew.edit("`🏃                     🐕`")
    await typew.edit("`🏃  Huh-Huh           🐕`")
    await typew.edit("`🏃                   🐕`")
    await typew.edit("`🏃                  🐕`")
    await typew.edit("`🏃                 🐕`")
    await typew.edit("`🏃                🐕`")
    await typew.edit("`🏃               🐕`")
    await typew.edit("`🏃              🐕`")
    await typew.edit("`🏃             🐕`")
    await typew.edit("`🏃            🐕`")
    await typew.edit("`🏃           🐕`")
    await typew.edit("`🏃          🐕`")
    await typew.edit("`🏃         🐕`")
    await typew.edit("`Ayo sedikit lagi!!`")
    sleep(1)
    await typew.edit("`🏃       🐕`")
    await typew.edit("`🏃      🐕`")
    await typew.edit("`🏃     🐕`")
    await typew.edit("`🏃    🐕`")
    await typew.edit("`Anjing pintar...`")
    sleep(1)
    await typew.edit("`🧎🐕`")
    sleep(2)
    await typew.edit("`-TamaT-`")


@register(outgoing=True, pattern="^.gabut$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("`Aduh gabut banget si`")
        sleep(1)
        await e.edit("`Hmm...`")
        sleep(1)
        await e.edit("`Enaknya ngapain ya...`")
        sleep(1)
        await e.edit("`Oiya!!`")
        sleep(1)
        await e.edit("`Mending gua jalan²`")
        sleep(1)
        await e.edit("`Daripada gabut...`")
        sleep(1)
        await e.edit("`Okelah berangkat...`")
        sleep(1)
        await e.edit("🚶‍♀                       🚶")
        await e.edit("🚶‍♀                      🚶")
        await e.edit("🚶‍♀                     🚶")
        await e.edit("🚶‍♀                    🚶")
        await e.edit("🚶‍♀                   🚶")
        await e.edit("🚶‍♀                  🚶")
        await e.edit("🚶‍♀                 🚶")
        await e.edit("🚶‍♀                🚶")
        await e.edit("🚶‍♀               🚶")
        await e.edit("🚶‍♀              🚶")
        await e.edit("🚶‍♀             🚶")
        await e.edit("🚶‍♀            🚶")
        await e.edit("🚶‍♀           🚶")
        await e.edit("🚶‍♀          🚶")
        await e.edit("🚶‍♀         🚶")
        await e.edit("🚶‍♀        🚶")
        await e.edit("🚶‍♀       🚶")
        await e.edit("🚶‍♀      🚶")
        await e.edit("🚶‍♀     🚶")
        await e.edit("🚶‍♀    🚶")
        await e.edit("🚶‍♀   🚶")
        await e.edit("🚶‍♀  🚶")
        await e.edit("🚶‍♀ 🚶")
        await e.edit("🚶‍♀🚶")
        await e.edit("🚶🚶‍♀")
        await e.edit("🚶 🚶‍♀")
        await e.edit("🚶  🚶‍♀")
        await e.edit("🚶   🚶‍♀")
        await e.edit("🚶    🚶‍♀")
        await e.edit("🚶     🚶‍♀")
        await e.edit("🚶      🚶‍♀")
        await e.edit("🚶       🚶‍♀")
        await e.edit("🚶        🚶‍♀")
        await e.edit("🚶         🚶‍♀")
        await e.edit("🚶          🚶‍♀")
        await e.edit("🚶           🚶‍♀")
        await e.edit("🚶            🚶‍♀")
        await e.edit("🚶             🚶‍♀")
        await e.edit("🚶              🚶‍♀")
        await e.edit("🚶               🚶‍♀")
        await e.edit("🚶                🚶‍♀")
        await e.edit("🚶                 🚶‍♀")
        await e.edit("🚶                  🚶‍♀")
        await e.edit("🚶                   🚶‍♀")
        await e.edit("🚶                    🚶‍♀")
        await e.edit("🚶                     🚶‍♀")
        await e.edit("🚶                      🚶‍♀")
        await e.edit("🚶                       🚶‍♀")
        await e.edit("🚶                        🚶‍♀")
        await e.edit("🚶                         🚶‍♀")
        await e.edit("🚶                          🚶‍♀")
        await e.edit("🚶                           🚶‍♀")
        await e.edit("🚶                            🚶‍♀")
        await e.edit("🚶                             🚶‍♀")
        await e.edit("🚶                              🚶‍♀")
        await e.edit("🚶                               🚶‍♀")
        await e.edit("🚶                                🚶‍♀")
        await e.edit("🚶                                 🚶‍♀")
        await e.edit("`Cape juga...`")
        sleep(1)
        await e.edit("👨‍🦽                       🚶")
        await e.edit("👨‍🦽                      🚶")
        await e.edit("👨‍🦽                     🚶")
        await e.edit("👨‍🦽                    🚶")
        await e.edit("👨‍🦽                   🚶")
        await e.edit("👨‍🦽                  🚶")
        await e.edit("👨‍🦽                 🚶")
        await e.edit("👨‍🦽                🚶")
        await e.edit("👨‍🦽               🚶")
        await e.edit("👨‍🦽              🚶")
        await e.edit("👨‍🦽             🚶")
        await e.edit("👨‍🦽            🚶")
        await e.edit("👨‍🦽           🚶")
        await e.edit("👨‍🦽          🚶")
        await e.edit("👨‍🦽         🚶")
        await e.edit("👨‍🦽        🚶")
        await e.edit("👨‍🦽       🚶")
        await e.edit("👨‍🦽      🚶")
        await e.edit("👨‍🦽     🚶")
        await e.edit("👨‍🦽    🚶")
        await e.edit("👨‍🦽   🚶")
        await e.edit("👨‍🦽  🚶")
        await e.edit("👨‍🦽 🚶")
        await e.edit("👨‍🦽🚶")
        await e.edit("🚶👨‍🦽")
        await e.edit("🚶 👨‍🦽")
        await e.edit("🚶  👨‍🦽")
        await e.edit("🚶   👨‍🦽")
        await e.edit("🚶    👨‍🦽")
        await e.edit("🚶     👨‍🦽")
        await e.edit("🚶      👨‍🦽")
        await e.edit("🚶       👨‍🦽")
        await e.edit("🚶        👨‍🦽")
        await e.edit("🚶         👨‍🦽")
        await e.edit("🚶          👨‍🦽")
        await e.edit("🚶           👨‍🦽")
        await e.edit("🚶            👨‍🦽")
        await e.edit("🚶             👨‍🦽")
        await e.edit("🚶              👨‍🦽")
        await e.edit("🚶               👨‍🦽")
        await e.edit("🚶                👨‍🦽")
        await e.edit("🚶                 👨‍🦽")
        await e.edit("🚶                  👨‍🦽")
        await e.edit("🚶                   👨‍🦽")
        await e.edit("🚶                    👨‍🦽")
        await e.edit("🚶                     👨‍🦽")
        await e.edit("🚶                      👨‍🦽")
        await e.edit("🚶                       👨‍🦽")
        await e.edit("🚶                        👨‍🦽")
        await e.edit("🚶                         👨‍🦽")
        await e.edit("🚶                          👨‍🦽")
        await e.edit("🚶                           👨‍🦽")
        await e.edit("🚶                            👨‍🦽")
        await e.edit("🚶                             👨‍🦽")
        await e.edit("🚶                              👨‍🦽")
        await e.edit("🚶                               👨‍🦽")
        await e.edit("🚶                                👨‍🦽")
        await e.edit("🚶‍♀                       🚶")
        await e.edit("🚶‍♀                      🚶")
        await e.edit("🚶‍♀                     🚶")
        await e.edit("🚶‍♀                    🚶")
        await e.edit("🚶‍♀                   🚶")
        await e.edit("🚶‍♀                  🚶")
        await e.edit("🚶‍♀                 🚶")
        await e.edit("🚶‍♀                🚶")
        await e.edit("🚶‍♀               🚶")
        await e.edit("🚶‍♀              🚶")
        await e.edit("🚶‍♀             🚶")
        await e.edit("🚶‍♀            🚶")
        await e.edit("🚶‍♀           🚶")
        await e.edit("🚶‍♀          🚶")
        await e.edit("🚶‍♀         🚶")
        await e.edit("🚶‍♀        🚶")
        await e.edit("🚶‍♀       🚶")
        await e.edit("🚶‍♀      🚶")
        await e.edit("🚶‍♀     🚶")
        await e.edit("🚶‍♀    🚶")
        await e.edit("🚶‍♀   🚶")
        await e.edit("🚶‍♀  🚶")
        await e.edit("🚶‍♀ 🚶")
        await e.edit("🚶‍♀🚶")
        await e.edit("🚶🚶‍♀")
        await e.edit("🚶 🚶‍♀")
        await e.edit("🚶  🚶‍♀")
        await e.edit("🚶   🚶‍♀")
        await e.edit("🚶    🚶‍♀")
        await e.edit("🚶     🚶‍♀")
        await e.edit("🚶      🚶‍♀")
        await e.edit("🚶       🚶‍♀")
        await e.edit("🚶        🚶‍♀")
        await e.edit("🚶         🚶‍♀")
        await e.edit("🚶          🚶‍♀")
        await e.edit("🚶           🚶‍♀")
        await e.edit("🚶            🚶‍♀")
        await e.edit("🚶             🚶‍♀")
        await e.edit("🚶              🚶‍♀")
        await e.edit("🚶               🚶‍♀")
        await e.edit("🚶                🚶‍♀")
        await e.edit("🚶                 🚶‍♀")
        await e.edit("🚶                  🚶‍♀")
        await e.edit("🚶                   🚶‍♀")
        await e.edit("🚶                    🚶‍♀")
        await e.edit("🚶                     🚶‍♀")
        await e.edit("🚶                      🚶‍♀")
        await e.edit("🚶                       🚶‍♀")
        await e.edit("🚶                        🚶‍♀")
        await e.edit("🚶                         🚶‍♀")
        await e.edit("🚶                          🚶‍♀")
        await e.edit("🚶                           🚶‍♀")
        await e.edit("🚶                            🚶‍♀")
        await e.edit("🚶                             🚶‍♀")
        await e.edit("🚶                              🚶‍♀")
        await e.edit("🚶                               🚶‍♀")
        await e.edit("🚶                                🚶‍♀")
        await e.edit("🌳                       🚶")
        await e.edit("🌳                      🚶")
        await e.edit("🌳                     🚶")
        await e.edit("🌳                    🚶")
        await e.edit("🌳                   🚶")
        await e.edit("🌳                  🚶")
        await e.edit("🌳                 🚶")
        await e.edit("🌳                🚶")
        await e.edit("🌳               🚶")
        await e.edit("🌳              🚶")
        await e.edit("🌳             🚶")
        await e.edit("🌳            🚶")
        await e.edit("🌳           🚶")
        await e.edit("🌳          🚶")
        await e.edit("🌳         🚶")
        await e.edit("🌳        🚶")
        await e.edit("🌳       🚶")
        await e.edit("🌳      🚶")
        await e.edit("🌳     🚶")
        await e.edit("🌳    🚶")
        await e.edit("🌳   🚶")
        await e.edit("🌳  🚶")
        await e.edit("🌳 🚶")
        await e.edit("🌳🚶")
        await e.edit("🚶🌳")
        await e.edit("🚶 🌳")
        await e.edit("🚶  🌳")
        await e.edit("🚶   🌳")
        await e.edit("🚶    🌳")
        await e.edit("🚶     🌳")
        await e.edit("🚶      🌳")
        await e.edit("🚶       🌳")
        await e.edit("🚶        🌳")
        await e.edit("🚶         🌳")
        await e.edit("🚶          🌳")
        await e.edit("🚶           🌳")
        await e.edit("🚶            🌳")
        await e.edit("🚶             🌳")
        await e.edit("🚶              🌳")
        await e.edit("🚶               🌳")
        await e.edit("🚶                🌳")
        await e.edit("🚶                 🌳")
        await e.edit("🚶                  🌳")
        await e.edit("🚶                   🌳")
        await e.edit("🚶                    🌳")
        await e.edit("🚶                     🌳")
        await e.edit("🚶                      🌳")
        await e.edit("🚶                       🌳")
        await e.edit("🚶                        🌳")
        await e.edit("🚶                         🌳")
        await e.edit("🚶                          🌳")
        await e.edit("🚶                           🌳")
        await e.edit("🚶                            🌳")
        await e.edit("🚶                             🌳")
        await e.edit("🚶                              🌳")
        await e.edit("🚶                               🌳")
        await e.edit("🚶                                🌳")
        await e.edit("`Dah ah cape...`")


@register(outgoing=True, pattern='^.terkadang(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`Terkadang`")
    sleep(1)
    await typew.edit("`Mencintai seseorang`")
    sleep(1)
    await typew.edit("`Hanya akan membuang waktumu`")
    sleep(1)
    await typew.edit("`Dan ketika waktumu habis`")
    sleep(1)
    await typew.edit("`Yaudah terima aja`")
    sleep(1)
    await typew.edit("`Hahaha...`")
# Create by myself @localheart


@bot.on(events.NewMessage(pattern=r"\.(.*)", outgoing=True))
async def _(event):

    if event.fwd_from:

        return

    animation_interval = 2

    animation_ttl = range(0, 11)

    input_str = event.pattern_match.group(1)

    if input_str == "cinta":

        await event.edit(input_str)

        animation_chars = [
            "`Connecting to server cinta...`",
            "`Mencari target cinta...`",
            "`Mengirim cintaku.. 0%\n▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim cintaku.. 4%\n█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim cintaku.. 8%\n██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim cintaku.. 20%\n█████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim cintaku.. 36%\n█████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim cintaku.. 52%\n█████████████▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`Mengirim cintaku.. 84%\n█████████████████████▒▒▒▒ `",
            "`Mengirim cintaku.. 100%\n█████████ 𝗟𝗼𝘃𝗲 ███████████ `",
            f"`Sekarang cintaku sudah terkirim sepenuhnya padamu, I love you 💞`"]

        for i in animation_ttl:

            await asyncio.sleep(animation_interval)

            await event.edit(animation_chars[i % 11])


@register(outgoing=True, pattern='^.gombal(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`Hai kamu...`")
    sleep(1)
    await typew.edit("`Sebenernya gua suka sama lu!`")
    sleep(1)
    await typew.edit("`Gua sayang sama lu!`")
    sleep(1)
    await typew.edit("`Gua rasa udah cukup gua diem!`")
    sleep(1)
    await typew.edit("`I love you💞`")
    sleep(1)
    await typew.edit("`I need you💖`")
    sleep(1)
    await typew.edit("`I miss you💗`")
    sleep(1)
    await typew.edit("`Jadi gimana?`")
    sleep(1)
    await typew.edit("`Mau ga jadi pacar gua?💘`")
    sleep(1)
    await typew.edit("`Tapi boong..`")
# Create by myself @localheart

CMD_HELP.update({
    "gabut":
    "`.gabut` ; `.anjing`\
    \nPenjelasan: ntahlah gabut doang.\
    \n\n`.gombal`\
    \nPenjelasan: gombalan maut.\
    \n\n`.cinta`\
    \nPenjelasan: mengirim cintamu ke seseorang.\
    \n\n`.sayang`\
    \nPenjelasan: pakboy cocok nih.\
    \n\n`.terkadang`\
    \nPenjelasan: iseng doang ini."
})
