from time import sleep
from userbot import CMD_HELP, bot
from userbot.events import register
from telethon import events
import asyncio


@register(outgoing=True, pattern="^.sayang$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("𝐈 𝐋𝐨𝐯𝐞 𝐘𝐨𝐮 💕")
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💘💞💗💕")
        await e.edit("💘💞💕💗")
        await e.edit("𝐈 𝐌𝐢𝐬𝐬 𝐘𝐨𝐮 💝💖💘")
        await e.edit("💝💘💓💗")
        await e.edit("💞💕💗💘")
        await e.edit("💘💞💕💗")
        await e.edit("𝐒𝐚𝐲𝐚𝐧𝐠")
        await e.edit("𝐊𝐚𝐦𝐮")
        await e.edit("𝐒𝐞𝐥𝐚𝐦𝐚𝐧𝐲𝐚 💕")
        await e.edit("💘💘💘💘")
        await e.edit("𝐒𝐚𝐲𝐚𝐧𝐠")
        await e.edit("𝐊𝐚𝐦𝐮")
        await e.edit("𝐒𝐚𝐲𝐚𝐧𝐠")
        await e.edit("𝐊𝐚𝐦𝐮")
        await e.edit("𝐈 𝐋𝐨𝐯𝐞 𝐘𝐨𝐮")
        await e.edit("𝐁𝐚𝐛𝐞𝐞𝐞")
        await e.edit("💕💞💘💝")
        await e.edit("💘💕💞💝")
        await e.edit("𝐒𝐚𝐲𝐚𝐧𝐠 𝐊𝐚𝐦𝐮💞")


@register(outgoing=True, pattern='^.anjing(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`𝐀𝐧𝐣𝐢𝐧𝐠 𝐆𝐮𝐚 𝐋𝐚𝐦𝐚 𝐀𝐦𝐚𝐭.....`")
    sleep(1)
    await typew.edit("`𝐃𝐨𝐠𝐠𝐲𝐲𝐲!!!`")
    sleep(1)
    await typew.edit("`🏃                        🐕`")
    await typew.edit("`🏃                       🐕`")
    await typew.edit("`🏃                      🐕`")
    await typew.edit("`🏃                     🐕`")
    await typew.edit("`🏃  `𝐂𝐞𝐩𝐚𝐭!!`          🐕`")
    await typew.edit("`🏃                   🐕`")
    await typew.edit("`🏃                  🐕`")
    await typew.edit("`🏃                 🐕`")
    await typew.edit("`🏃                🐕`")
    await typew.edit("`🏃               🐕`")
    await typew.edit("`🏃              🐕`")
    await typew.edit("`🏃             🐕`")
    await typew.edit("`🏃            🐕`")
    await typew.edit("`🏃           🐕`")
    await typew.edit("`🏃𝐀𝐲𝐨𝐨𝐨!!!   🐕`")
    await typew.edit("`🏃           🐕`")
    await typew.edit("`🏃            🐕`")
    await typew.edit("`🏃             🐕`")
    await typew.edit("`🏃              🐕`")
    await typew.edit("`🏃               🐕`")
    await typew.edit("`🏃                🐕`")
    await typew.edit("`🏃                 🐕`")
    await typew.edit("`🏃                  🐕`")
    await typew.edit("`🏃                   🐕`")
    await typew.edit("`🏃                    🐕`")
    await typew.edit("`🏃                     🐕`")
    await typew.edit("`🏃  𝐇𝐮𝐡-𝐇𝐮𝐡           🐕`")
    await typew.edit("`🏃                   🐕`")
    await typew.edit("`🏃                  🐕`")
    await typew.edit("`🏃                 🐕`")
    await typew.edit("`🏃                🐕`")
    await typew.edit("`🏃               🐕`")
    await typew.edit("`🏃              🐕`")
    await typew.edit("`🏃             🐕`")
    await typew.edit("`🏃            🐕`")
    await typew.edit("`🏃           🐕`")
    await typew.edit("`🏃          🐕`")
    await typew.edit("`🏃         🐕`")
    await typew.edit("`𝐀𝐲𝐨 𝐒𝐞𝐝𝐢𝐤𝐢𝐭 𝐋𝐚𝐠𝐢!!`")
    sleep(1)
    await typew.edit("`🏃       🐕`")
    await typew.edit("`🏃      🐕`")
    await typew.edit("`🏃     🐕`")
    await typew.edit("`🏃    🐕`")
    await typew.edit("`𝐀𝐧𝐣𝐢𝐧𝐠 𝐏𝐢𝐧𝐭𝐚𝐫...`")
    sleep(1)
    await typew.edit("`🧎🐕`")
    sleep(2)
    await typew.edit("`-𝐓𝐨𝐤𝐚𝐢-`")


@register(outgoing=True, pattern="^.gabut$")
async def koc(e):
    if not e.text[0].isalpha() and e.text[0] not in ("/", "#", "@", "!"):
        await e.edit("`𝐀𝐝𝐮𝐡𝐡 𝐠𝐚𝐛𝐮𝐭 𝐛𝐚𝐧𝐠𝐞𝐭 𝐬𝐢`")
        await e.edit("`𝐇𝐦𝐦...`")
        await e.edit("`𝐆𝐮𝐚 𝐡𝐚𝐫𝐮𝐬 𝐧𝐠𝐚𝐩𝐚𝐢𝐧 𝐲𝐚𝐚...`")
        await e.edit("`𝐎𝐢𝐲𝐚𝐚!!`")
        await e.edit("`𝐌𝐞𝐧𝐝𝐢𝐧𝐠 𝐠𝐮𝐚 𝐣𝐚𝐥𝐚𝐧²`")
        await e.edit("`𝐃𝐚𝐫𝐢𝐩𝐚𝐝𝐚 𝐠𝐚𝐛𝐮𝐭...`")
        await e.edit("`𝐎𝐤𝐞𝐞 𝐛𝐞𝐫𝐚𝐧𝐠𝐤𝐚𝐭...`")
        await e.edit("🐈                       🚶")
        await e.edit("🐈                      🚶")
        await e.edit("🐈                     🚶")
        await e.edit("🐈                    🚶")
        await e.edit("🐈                   🚶")
        await e.edit("🐈                  🚶")
        await e.edit("🐈                 🚶")
        await e.edit("🐈                🚶")
        await e.edit("🐈               🚶")
        await e.edit("🐈              🚶")
        await e.edit("🐈             🚶")
        await e.edit("🐈            🚶")
        await e.edit("🐈           🚶")
        await e.edit("🐈          🚶")
        await e.edit("🐈         🚶")
        await e.edit("🐈        🚶")
        await e.edit("🐈       🚶")
        await e.edit("🐈      🚶")
        await e.edit("🐈     🚶")
        await e.edit("🐈    🚶")
        await e.edit("🐈   🚶")
        await e.edit("🐈  🚶")
        await e.edit("🐈 🚶")
        await e.edit("🐈🚶")
        await e.edit("🚶🐈")
        await e.edit("🚶 🐈")
        await e.edit("🚶  🐈")
        await e.edit("🚶   🐈")
        await e.edit("🚶    🐈")
        await e.edit("🚶     🐈")
        await e.edit("🚶      🐈")
        await e.edit("🚶       🐈")
        await e.edit("🚶        🐈")
        await e.edit("🚶         🐈")
        await e.edit("🚶          🐈")
        await e.edit("🚶           🐈")
        await e.edit("🚶            🐈")
        await e.edit("🚶             🐈")
        await e.edit("🚶              🐈")
        await e.edit("🚶               🐈")
        await e.edit("🚶                🐈")
        await e.edit("🚶                 🐈")
        await e.edit("🚶                  🐈")
        await e.edit("🚶                   🐈")
        await e.edit("🚶                    🐈")
        await e.edit("🚶                     🐈")
        await e.edit("🚶                      🐈")
        await e.edit("🚶                       🐈")
        await e.edit("🚶                        🐈")
        await e.edit("🚶                         🐈")
        await e.edit("🚶                          🐈")
        await e.edit("🚶                           🐈")
        await e.edit("🚶                            🐈")
        await e.edit("🚶                             🐈")
        await e.edit("🚶                              🐈")
        await e.edit("🚶                               🐈")
        await e.edit("🚶                                🐈")
        await e.edit("🚶                                 🐈")
        await e.edit("`𝐂𝐚𝐩𝐞𝐞 𝐣𝐮𝐠𝐚...`")
        await e.edit("🐈                       🚶")
        await e.edit("🐈                      🚶")
        await e.edit("🐈                     🚶")
        await e.edit("🐈                    🚶")
        await e.edit("🐈                   🚶")
        await e.edit("🐈                  🚶")
        await e.edit("🐈                 🚶")
        await e.edit("🐈                🚶")
        await e.edit("🐈               🚶")
        await e.edit("🐈              🚶")
        await e.edit("🐈             🚶")
        await e.edit("🐈            🚶")
        await e.edit("🐈           🚶")
        await e.edit("🐈          🚶")
        await e.edit("🐈         🚶")
        await e.edit("🐈        🚶")
        await e.edit("🐈       🚶")
        await e.edit("🐈      🚶")
        await e.edit("🐈     🚶")
        await e.edit("🐈    🚶")
        await e.edit("🐈   🚶")
        await e.edit("🐈  🚶")
        await e.edit("🐈 🚶")
        await e.edit("🐈🚶")
        await e.edit("🚶🐈")
        await e.edit("🚶 🐈")
        await e.edit("🚶  🐈")
        await e.edit("🚶   🐈")
        await e.edit("🚶    🐈")
        await e.edit("🚶     🐈")
        await e.edit("🚶      🐈")
        await e.edit("🚶       🐈")
        await e.edit("🚶        🐈")
        await e.edit("🚶         🐈")
        await e.edit("🚶          🐈")
        await e.edit("🚶           🐈")
        await e.edit("🚶            🐈")
        await e.edit("🚶             🐈")
        await e.edit("🚶              🐈")
        await e.edit("🚶               🐈")
        await e.edit("🚶                🐈")
        await e.edit("🚶                 🐈")
        await e.edit("🚶                  🐈")
        await e.edit("🚶                   🐈")
        await e.edit("🚶                    🐈")
        await e.edit("🚶                     🐈")
        await e.edit("🚶                      🐈")
        await e.edit("🚶                       🐈")
        await e.edit("🚶                        🐈")
        await e.edit("🚶                         🐈")
        await e.edit("🚶                          🐈")
        await e.edit("🚶                           🐈")
        await e.edit("🚶                            🐈")
        await e.edit("🚶                             🐈")
        await e.edit("🚶                              🐈")
        await e.edit("🚶                               🐈")
        await e.edit("🚶                                🐈")
        await e.edit("🐈                       🚶")
        await e.edit("🐈                      🚶")
        await e.edit("🐈                     🚶")
        await e.edit("🐈                    🚶")
        await e.edit("🐈                   🚶")
        await e.edit("🐈                  🚶")
        await e.edit("🐈                 🚶")
        await e.edit("🐈                🚶")
        await e.edit("🐈               🚶")
        await e.edit("🐈              🚶")
        await e.edit("🐈             🚶")
        await e.edit("🐈            🚶")
        await e.edit("🐈           🚶")
        await e.edit("🐈          🚶")
        await e.edit("🐈         🚶")
        await e.edit("🐈        🚶")
        await e.edit("🐈       🚶")
        await e.edit("🐈      🚶")
        await e.edit("🐈     🚶")
        await e.edit("🐈    🚶")
        await e.edit("🐈   🚶")
        await e.edit("🐈  🚶")
        await e.edit("🐈 🚶")
        await e.edit("🐈🚶")
        await e.edit("🚶🐈")
        await e.edit("🚶 🐈")
        await e.edit("🚶  🐈")
        await e.edit("🚶   🐈")
        await e.edit("🚶    🐈")
        await e.edit("🚶     🐈")
        await e.edit("🚶      🐈")
        await e.edit("🚶       🐈")
        await e.edit("🚶        🐈")
        await e.edit("🚶         🐈")
        await e.edit("🚶          🐈")
        await e.edit("🚶           🐈")
        await e.edit("🚶            🐈")
        await e.edit("🚶             🐈")
        await e.edit("🚶              🐈")
        await e.edit("🚶               🐈")
        await e.edit("🚶                🐈")
        await e.edit("🚶                 🐈")
        await e.edit("🚶                  🐈")
        await e.edit("🚶                   🐈")
        await e.edit("🚶                    🐈")
        await e.edit("🚶                     🐈")
        await e.edit("🚶                      🐈")
        await e.edit("🚶                       🐈")
        await e.edit("🚶                        🐈")
        await e.edit("🚶                         🐈")
        await e.edit("🚶                          🐈")
        await e.edit("🚶                           🐈")
        await e.edit("🚶                            🐈")
        await e.edit("🚶                             🐈")
        await e.edit("🚶                              🐈")
        await e.edit("🚶                               🐈")
        await e.edit("🚶                                🐈")
        await e.edit("🐈                       🚶")
        await e.edit("🐈                      🚶")
        await e.edit("🐈                     🚶")
        await e.edit("🐈                    🚶")
        await e.edit("🐈                   🚶")
        await e.edit("🐈                  🚶")
        await e.edit("🐈                 🚶")
        await e.edit("🐈                🚶")
        await e.edit("🐈               🚶")
        await e.edit("🐈              🚶")
        await e.edit("🐈             🚶")
        await e.edit("🐈            🚶")
        await e.edit("🐈           🚶")
        await e.edit("🐈          🚶")
        await e.edit("🐈         🚶")
        await e.edit("🐈        🚶")
        await e.edit("🐈       🚶")
        await e.edit("🐈      🚶")
        await e.edit("🐈     🚶")
        await e.edit("🐈    🚶")
        await e.edit("🐈   🚶")
        await e.edit("🐈  🚶")
        await e.edit("🐈 🚶")
        await e.edit("🐈🚶")
        await e.edit("🚶🐈")
        await e.edit("🚶 🐈")
        await e.edit("🚶  🐈")
        await e.edit("🚶   🐈")
        await e.edit("🚶    🐈")
        await e.edit("🚶     🐈")
        await e.edit("🚶      🐈")
        await e.edit("🚶       🐈")
        await e.edit("🚶        🐈")
        await e.edit("🚶         🐈")
        await e.edit("🚶          🐈")
        await e.edit("🚶           🐈")
        await e.edit("🚶            🐈")
        await e.edit("🚶             🐈")
        await e.edit("🚶              🐈")
        await e.edit("🚶               🐈")
        await e.edit("🚶                🐈")
        await e.edit("🚶                 🐈")
        await e.edit("🚶                  🐈")
        await e.edit("🚶                   🐈")
        await e.edit("🚶                    🐈")
        await e.edit("🚶                     🐈")
        await e.edit("🚶                      🐈")
        await e.edit("🚶                       🐈")
        await e.edit("🚶                        🐈")
        await e.edit("🚶                         🐈")
        await e.edit("🚶                          🐈")
        await e.edit("🚶                           🐈")
        await e.edit("🚶                            🐈")
        await e.edit("🚶                             🐈")
        await e.edit("🚶                              🐈")
        await e.edit("🚶                               🐈")
        await e.edit("🚶                                🐈")
        await e.edit("`𝐂𝐚𝐩𝐞𝐞...`")


@register(outgoing=True, pattern='^.terkadang(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("`𝐓𝐞𝐫𝐤𝐚𝐝𝐚𝐧𝐠`")
    sleep(1)
    await typew.edit("`𝐌𝐞𝐧𝐜𝐢𝐧𝐭𝐚𝐢 𝐬𝐞𝐬𝐞𝐨𝐫𝐚𝐧𝐠`")
    sleep(1)
    await typew.edit("`𝐇𝐚𝐧𝐲𝐚 𝐚𝐤𝐚𝐧 𝐦𝐞𝐦𝐛𝐮𝐚𝐧𝐠 𝐰𝐚𝐤𝐭𝐮𝐦𝐮`")
    sleep(1)
    await typew.edit("`𝐃𝐚𝐧 𝐤𝐞𝐭𝐢𝐤𝐚 𝐰𝐚𝐤𝐭𝐮𝐦𝐮 𝐡𝐚𝐛𝐢𝐬`")
    sleep(1)
    await typew.edit("`𝐘𝐚𝐮𝐝𝐚𝐡 𝐭𝐞𝐫𝐢𝐦𝐚 𝐚𝐣𝐚`")
    sleep(1)
    await typew.edit("`𝐖𝐤𝐰𝐤𝐰𝐤𝐰𝐤𝐰𝐤`")
# Create by myself @localheart


@bot.on(events.NewMessage(pattern=r"\.(.*)", outgoing=True))
async def _(event):

    if event.fwd_from:

        return

    animation_interval = 2

    animation_ttl = range(0, 11)

    input_str = event.pattern_match.group(1)

    if input_str == "cinta":

        await event.edit(input_str)

        animation_chars = [
            "`𝐂𝐨𝐧𝐧𝐞𝐜𝐭𝐢𝐧𝐠 𝐒𝐞 𝐒𝐞𝐫𝐯𝐞𝐫 𝐂𝐢𝐧𝐭𝐚`",
            "`𝐌𝐞𝐧𝐜𝐚𝐫𝐢 𝐓𝐚𝐫𝐠𝐞𝐭 𝐂𝐢𝐧𝐭𝐚`",
            "`𝐌𝐞𝐧𝐠𝐢𝐫𝐢𝐦 𝐂𝐢𝐧𝐭𝐚𝐤𝐮.. 0%\n▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`𝐌𝐞𝐧𝐠𝐢𝐫𝐢𝐦 𝐂𝐢𝐧𝐭𝐚𝐤𝐮.. 4%\n█▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`𝐌𝐞𝐧𝐠𝐢𝐫𝐢𝐦 𝐂𝐢𝐧𝐭𝐚𝐤𝐮.. 8%\n██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`𝐌𝐞𝐧𝐠𝐢𝐫𝐢𝐦 𝐂𝐢𝐧𝐭𝐚𝐤𝐮.. 20%\n█████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`𝐌𝐞𝐧𝐠𝐢𝐫𝐢𝐦 𝐂𝐢𝐧𝐭𝐚𝐤𝐮.. 36%\n█████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`𝐌𝐞𝐧𝐠𝐢𝐫𝐢𝐦 𝐂𝐢𝐧𝐭𝐚𝐤𝐮.. 52%\n█████████████▒▒▒▒▒▒▒▒▒▒▒▒ `",
            "`𝐌𝐞𝐧𝐠𝐢𝐫𝐢𝐦 𝐂𝐢𝐧𝐭𝐚𝐤𝐮.. 84%\n█████████████████████▒▒▒▒ `",
            "`𝐌𝐞𝐧𝐠𝐢𝐫𝐢𝐦 𝐂𝐢𝐧𝐭𝐚𝐤𝐮.. 100%\n█████████ 𝐋𝐨𝐯𝐞 ███████████ `",
            f"`𝐂𝐢𝐧𝐭𝐚𝐤𝐮 𝐒𝐞𝐤𝐚𝐫𝐚𝐧𝐠 𝐒𝐞𝐩𝐞𝐧𝐮𝐡𝐧𝐲𝐚 𝐓𝐞𝐫𝐤𝐢𝐫𝐢𝐦 𝐏𝐚𝐝𝐚𝐦𝐮, 𝐃𝐚𝐧 𝐒𝐞𝐤𝐚𝐫𝐚𝐧𝐠 𝐀𝐤𝐮 𝐒𝐚𝐧𝐠𝐚𝐭 𝐌𝐞𝐧𝐜𝐢𝐧𝐭𝐚𝐢 𝐌𝐮, 𝐈 𝐋𝐨𝐯𝐞 𝐘𝐨𝐮 💞`"]

        for i in animation_ttl:

            await asyncio.sleep(animation_interval)

            await event.edit(animation_chars[i % 11])


@register(outgoing=True, pattern='^.gombal(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    sleep(1)
    await typew.edit("`𝐇𝐚𝐢 𝐤𝐚𝐦𝐮𝐮...`")
    sleep(1)
    await typew.edit("`𝐒𝐞𝐛𝐞𝐧𝐞𝐫𝐧𝐲𝐚 𝐠𝐮𝐚 𝐬𝐚𝐲𝐚𝐧𝐠 𝐬𝐚𝐦𝐚 𝐥𝐮!`")
    sleep(1)
    await typew.edit("`𝐆𝐮𝐚 𝐬𝐮𝐤𝐚 𝐬𝐚𝐦𝐚 𝐥𝐮!`")
    sleep(1)
    await typew.edit("`𝐆𝐮𝐚 𝐫𝐚𝐬𝐚 𝐮𝐝𝐚𝐡 𝐜𝐮𝐤𝐮𝐩 𝐠𝐮𝐚 𝐝𝐢𝐞𝐦!`")
    sleep(1)
    await typew.edit("`𝐈 𝐋𝐨𝐯𝐞 𝐘𝐨𝐮💞`")
    sleep(1)
    await typew.edit("`𝐈 𝐍𝐞𝐞𝐝 𝐘𝐨𝐮💖`")
    sleep(1)
    await typew.edit("`𝐈 𝐌𝐢𝐬𝐬 𝐘𝐨𝐮💗`")
    sleep(1)
    await typew.edit("`𝐒𝐨.... 𝐣𝐚𝐝𝐢 𝐠𝐢𝐦𝐚𝐧𝐚?`")
    sleep(1)
    await typew.edit("`𝐌𝐚𝐮 𝐧𝐠𝐠𝐚 𝐣𝐚𝐝𝐢 𝐩𝐚𝐜𝐚𝐫𝐤𝐮?💘`")
    sleep(1)
    await typew.edit("`𝐓𝐚𝐩𝐢 𝐁𝐨'𝐨𝐧𝐠 𝐇𝐞𝐡𝐞`")
# Create by myself @localheart

CMD_HELP.update({
    "gabut":
    "`.gabut` ; `.anjing`\
    \nPenjelasan: ntahlah gabut doang.\
    \n\n`.gombal`\
    \nPenjelasan: gombalan maut.\
    \n\n`.cinta`\
    \nPenjelasan: mengirim cintamu ke seseorang.\
    \n\n`.sayang`\
    \nPenjelasan: pakboy cocok nih.\
    \n\n`.terkadang`\
    \nPenjelasan: iseng doang ini."
})
